"""hello last db migration

Revision ID: 01499b102082
Revises: 52a3fe69c3da
Create Date: 2024-07-24 08:27:49.600533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01499b102082'
down_revision: Union[str, None] = '52a3fe69c3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_blocked_task_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'blocked_task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked_task', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_blocked_task_fkey', 'users', 'task', ['blocked_task'], ['id'])
    # ### end Alembic commands ###
