"""hello last db migration

Revision ID: 1c294729e6da
Revises: 23536d6f9235
Create Date: 2024-07-25 19:39:54.104250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c294729e6da'
down_revision: Union[str, None] = '23536d6f9235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TaskTag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TaskTag',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='TaskTag_tag_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='TaskTag_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='TaskTag_user_id_fkey'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', name='TaskTag_pkey')
    )
    # ### end Alembic commands ###
