"""hello last db migration

Revision ID: 23536d6f9235
Revises: 9d385e6ed24d
Create Date: 2024-07-25 19:25:15.203805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23536d6f9235'
down_revision: Union[str, None] = '9d385e6ed24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TaskTag', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'TaskTag', 'users', ['user_id'], ['id'])
    op.add_column('task', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'tag_id')
    op.drop_constraint(None, 'TaskTag', type_='foreignkey')
    op.drop_column('TaskTag', 'user_id')
    # ### end Alembic commands ###
