"""add completed comlumn

Revision ID: ddda82617c6e
Revises: 1c294729e6da
Create Date: 2024-07-28 06:36:05.256069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddda82617c6e'
down_revision: Union[str, None] = '1c294729e6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('subtasks', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed')
    op.drop_column('subtasks', 'completed')
    op.drop_column('project', 'completed')
    # ### end Alembic commands ###
